version: '3.3'

services:

  clientes-app:
    image: cajero-multimoneda/clientes-app:1.0.0
    build:
      context: .
      dockerfile: ./clientes/Dockerfile
    container_name: clientes-app
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - cajero-network
    ports:
      - "8000:8080"

  cuentas-app:
    image: cajero-multimoneda/cuentas-app:1.0.0
    build:
      context: .
      dockerfile: ./cuentas/Dockerfile
    container_name: cuentas-app
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - cajero-network
    ports:
      - "8001:8080"

  transacciones-app:
    image: cajero-multimoneda/transacciones-app:1.0.0
    build:
      context: .
      dockerfile: ./transacciones/Dockerfile
    container_name: transacciones-app
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - cajero-network
    ports:
      - "8002:8080"

  tasas-app:
    image: cajero-multimoneda/tasas-app:1.0.0
    build:
      context: .
      dockerfile: ./tasas/Dockerfile
    container_name: tasas-app
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - cajero-network
    ports:
      - "8003:8080"

networks:
  cajero-network:
    driver: bridge
