spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/cuentas-database
    username: cuentasUser
    password: cuentas1234
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: cliente-group
connections:
  gateway: http://localhost:8080
server:
  port: 8070
