spring:
  data:
    mongodb:
      host: clientes-database
      port: 27017
      database: clientes-database
      username: clientesUser
      password: clientes1234
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: cliente-group
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
