spring:
  data:
    mongodb:
      host: localhost
      port: 27027
      database: clientes-database
      username: clientesUser
      password: clientes1234
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: cliente-group
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
server:
  port: 8000
